const structures = [
  {
    id: 'glider',
    name: 'Glider',
    description: 'A tiny spaceship that drifts diagonally across the field.',
    cells: [
      [1, 0],
      [2, 1],
      [0, 2],
      [1, 2],
      [2, 2],
    ],
  },
  {
    id: 'boat',
    name: 'Boat',
    description: 'A small stable pattern that quietly holds its shape.',
    cells: [
      [0, 0],
      [1, 0],
      [0, 1],
      [2, 1],
      [1, 2],
    ],
  },
  {
    id: 'toad',
    name: 'Toad',
    description: 'A six-cell oscillator that flips between two phases.',
    cells: [
      [1, 0],
      [2, 0],
      [3, 0],
      [0, 1],
      [1, 1],
      [2, 1],
    ],
  },
  {
    id: 'beacon',
    name: 'Beacon',
    description: 'Two stable corners that pulse around a dark center.',
    cells: [
      [0, 0],
      [1, 0],
      [0, 1],
      [1, 1],
      [2, 2],
      [3, 2],
      [2, 3],
      [3, 3],
    ],
  },
  {
    id: 'lightweight-spaceship',
    name: 'Lightweight Spaceship',
    description: 'A classic moving ship that sweeps across the grid.',
    cells: [
      [1, 0],
      [4, 0],
      [0, 1],
      [0, 2],
      [4, 2],
      [0, 3],
      [1, 3],
      [2, 3],
      [3, 3],
    ],
  },
  {
    id: 'pulsar',
    name: 'Pulsar',
    description: 'A larger period-3 oscillator with a dramatic circular rhythm.',
    cells: [
      [2, 0],
      [3, 0],
      [4, 0],
      [8, 0],
      [9, 0],
      [10, 0],
      [0, 2],
      [5, 2],
      [7, 2],
      [12, 2],
      [0, 3],
      [5, 3],
      [7, 3],
      [12, 3],
      [0, 4],
      [5, 4],
      [7, 4],
      [12, 4],
      [2, 5],
      [3, 5],
      [4, 5],
      [8, 5],
      [9, 5],
      [10, 5],
      [2, 7],
      [3, 7],
      [4, 7],
      [8, 7],
      [9, 7],
      [10, 7],
      [0, 8],
      [5, 8],
      [7, 8],
      [12, 8],
      [0, 9],
      [5, 9],
      [7, 9],
      [12, 9],
      [0, 10],
      [5, 10],
      [7, 10],
      [12, 10],
      [2, 12],
      [3, 12],
      [4, 12],
      [8, 12],
      [9, 12],
      [10, 12],
    ],
  },
  {
    id: 'gosper-glider-gun',
    name: 'Gosper Glider Gun',
    description: 'A famous generator that keeps launching gliders forever.',
    cells: [
      [0, 4],
      [0, 5],
      [1, 4],
      [1, 5],
      [10, 4],
      [10, 5],
      [10, 6],
      [11, 3],
      [11, 7],
      [12, 2],
      [12, 8],
      [13, 2],
      [13, 8],
      [14, 5],
      [15, 3],
      [15, 7],
      [16, 4],
      [16, 5],
      [16, 6],
      [17, 5],
      [20, 2],
      [20, 3],
      [20, 4],
      [21, 2],
      [21, 3],
      [21, 4],
      [22, 1],
      [22, 5],
      [24, 0],
      [24, 1],
      [24, 5],
      [24, 6],
      [34, 2],
      [34, 3],
      [35, 2],
      [35, 3],
    ],
  },
];

function enrichStructure(structure) {
  const width = structure.cells.reduce((max, [x]) => Math.max(max, x), 0) + 1;
  const height = structure.cells.reduce((max, [, y]) => Math.max(max, y), 0) + 1;

  return {
    ...structure,
    width,
    height,
    cellCount: structure.cells.length,
  };
}

const structuredPatterns = structures.map(enrichStructure);
const structuresById = new Map(structuredPatterns.map((structure) => [structure.id, structure]));

module.exports = {
  structures: structuredPatterns,
  structuresById,
};
